"""Publication figures for the workshop paper.

Reads the finished ``runs/exp3_dynamic_500k`` artifacts (read-only) and writes
vector PDFs into ``paper/figures/``.  No simulation is run here; every number
is taken from the cached run outputs or the SQLite sample caches.  The
convergence, exploitability, and heatmap figures need ``online_runs/``, which
is regenerated by ``scripts/exp3_sequence_results.py`` (see README).

Usage (from repo root):

    .venv/bin/python scripts/make_paper_figures.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

REPO = Path(__file__).resolve().parents[1]
RUN = REPO / "runs" / "exp3_dynamic_500k"
OUT = REPO / "paper" / "figures"

# ---------------------------------------------------------------------------
# Style: validated categorical palette (fixed slot order), status colors,
# recessive chrome.  Sized for an IEEE conference column (~3.42 in).
# ---------------------------------------------------------------------------
COLUMN_IN = 3.42

INK = "#0b0b0b"
INK_2 = "#52514e"
MUTED = "#898781"
GRID = "#e1e0d9"
AXIS = "#c3c2b7"

CATEGORICAL = [
    "#2a78d6",  # 1 blue
    "#1baf7a",  # 2 aqua
    "#eda100",  # 3 yellow
    "#008300",  # 4 green
    "#4a3aa7",  # 5 violet
    "#e34948",  # 6 red
    "#e87ba4",  # 7 magenta
    "#eb6834",  # 8 orange
]

# Fixed family -> (color slot, marker) assignment, reused across all figures.
# Order is chosen so families that share a plot (notably the four convergence
# examples) land on well-separated hues; it never changes between figures.
FAMILIES = [
    "disjoint_parallel",   # blue
    "wheatstone_chain",    # aqua
    "single_bottleneck",   # yellow
    "layered_parallel",    # green
    "deep_parallel",       # violet
    "multi_bottleneck",    # red
    "length_variant",      # magenta
    "deep_bottleneck",     # orange
]
FAMILY_COLOR = {fam: CATEGORICAL[i] for i, fam in enumerate(FAMILIES)}
FAMILY_MARKER = {
    "deep_bottleneck": "v",
    "deep_parallel": "o",
    "disjoint_parallel": "s",
    "layered_parallel": "D",
    "length_variant": "^",
    "multi_bottleneck": "X",
    "single_bottleneck": "P",
    "wheatstone_chain": "d",
}

BOTTLENECK_RED = "#d03b3b"

plt.rcParams.update({
    "font.size": 8,
    "axes.labelsize": 8,
    "axes.titlesize": 8,
    "xtick.labelsize": 7,
    "ytick.labelsize": 7,
    "legend.fontsize": 6.5,
    "axes.edgecolor": AXIS,
    "axes.linewidth": 0.6,
    "axes.labelcolor": INK,
    "text.color": INK,
    "xtick.color": INK_2,
    "ytick.color": INK_2,
    "xtick.major.size": 2.5,
    "ytick.major.size": 2.5,
    "grid.color": GRID,
    "grid.linewidth": 0.5,
    "legend.frameon": False,
    "pdf.fonttype": 42,
    "ps.fonttype": 42,
})


def _tidy(ax) -> None:
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.grid(True, alpha=0.8)
    ax.set_axisbelow(True)


def _family_of(graph_id: str, families: dict[str, str]) -> str:
    return families[graph_id]


def load_run() -> dict:
    corpus = json.loads((RUN / "corpus.json").read_text())
    oracle = json.loads((RUN / "oracle_summary.json").read_text())
    graphs = {g["graph_id"]: g for g in corpus["graphs"]}
    online = {}
    for path in sorted((RUN / "online_runs" / "exp3_vs_exp3").glob("*.json")):
        d = json.loads(path.read_text())
        online[d["graph_id"]] = d
    return {"graphs": graphs, "oracle": oracle, "online": online}


# ---------------------------------------------------------------------------
# Fig 1: route-depth diagnostics from the SQLite sample caches
# ---------------------------------------------------------------------------

def fig_attack_depth() -> None:
    import sys

    sys.path.insert(0, str(REPO))
    from sequence_game.experiments.exp3_sequence.attack_cache import (
        attack_cache_hop_statistics,
    )
    from sequence_game.experiments.exp3_sequence.baseline_cache import (
        baseline_cache_hop_statistics,
    )

    attack_rows = attack_cache_hop_statistics(
        REPO / "sequence_game" / "experiments" / "exp3_sequence"
        / "attack_baselines.sqlite")
    baseline_rows = baseline_cache_hop_statistics(
        REPO / "sequence_game" / "experiments" / "exp3_sequence"
        / "baselines_fidelity_0p98.sqlite")

    series: list[tuple[str, str, list[dict]]] = [
        ("no attack", INK_2, baseline_rows),
    ]
    by_kind: dict[str, list[dict]] = {}
    for row in attack_rows:
        by_kind.setdefault(str(row["attack_kind"]), []).append(row)
    kind_style = {
        "edge_intercept_resend": ("intercept–resend", "#e34948"),
        "memory_degradation": ("memory degradation", "#2a78d6"),
    }
    for kind in sorted(by_kind):
        label, color = kind_style.get(kind, (kind, INK))
        series.append((label, color, by_kind[kind]))

    fig, ax_s = plt.subplots(figsize=(COLUMN_IN, 2.2),
                             constrained_layout=True)

    for label, color, rows in series:
        rows = sorted(rows, key=lambda r: int(r["hop_count"]))
        hops = np.array([int(r["hop_count"]) for r in rows])
        mean = np.array([float(r["mean_abs_chsh_s"]) for r in rows])
        sd = np.array([float(r["sd_abs_chsh_s"]) for r in rows])
        ax_s.fill_between(hops, np.maximum(0, mean - sd), mean + sd,
                          color=color, alpha=0.12, linewidth=0)
        ax_s.plot(hops, mean, color=color, linewidth=1.5, label=label)

    ax_s.axhline(2.0, color=INK, linestyle=(0, (2, 2)), linewidth=0.8)
    ax_s.text(7.35, 2.06, "Bell bound $|S|=2$", ha="right", va="bottom",
              fontsize=6.5, color=INK_2)

    ax_s.set_ylabel(r"mean $|S|$  ($\pm$1 sd)")
    ax_s.set_ylim(0, 3.05)
    ax_s.set_xlabel("route length (hops)")
    ax_s.set_xticks(range(1, 8))
    fig.legend(loc="outside upper center", ncol=3, handlelength=1.3,
               columnspacing=1.0, handletextpad=0.5)
    _tidy(ax_s)
    fig.savefig(OUT / "fig_attack_depth.pdf")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Fig 2: selected Exp3 convergence (Nash gap + sampled retention)
# ---------------------------------------------------------------------------

SELECTED = [
    "disjoint_parallel_2_v0",
    "wheatstone_chain_1_v0",
    "multi_bottleneck_2x4_v0",
    "layered_parallel_2x3_v0",
]


# Per-figure line colors (validated CVD-safe set: hunter green, blue,
# sunset orange, red); the figure's own legend carries family identity.
CONVERGENCE_COLOR = {
    "disjoint_parallel": "#2a78d6",   # blue
    "wheatstone_chain": "#c25e00",    # dark sunset orange
    "multi_bottleneck": "#e34948",    # red
    "layered_parallel": "#2e7d32",    # hunter green
}


def fig_convergence(data: dict) -> None:
    fig, ax_gap = plt.subplots(figsize=(COLUMN_IN, 2.1),
                               constrained_layout=True)

    stride = 20
    for graph_id in SELECTED:
        run = data["online"][graph_id]
        case = data["graphs"][graph_id]
        fam = case["family"]
        curve = run["learning_curve"][::stride]
        turns = np.array([row["turn"] for row in curve]) / 1e3
        gap = np.array([max(row["exploitability"], 1e-6) for row in curve])
        feats = case["features"]
        label = (f"{fam.replace('_', ' ')} "
                 f"(N={feats['node_disjoint_paths']:.0f}, "
                 f"h={feats['longest_hops']:.0f})")
        ax_gap.plot(turns, gap, color=CONVERGENCE_COLOR[fam], linewidth=1.2,
                    label=label)

    ax_gap.set_yscale("log")
    ax_gap.set_ylabel("Nash gap (averaged strategies)")
    ax_gap.set_xlabel(r"turn ($\times 10^3$)")
    ax_gap.legend(loc="upper right", handlelength=1.3, borderaxespad=0.2,
                  labelspacing=0.3)
    _tidy(ax_gap)
    fig.savefig(OUT / "fig_convergence.pdf")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Fig 3: oracle retention vs node-disjoint paths
# ---------------------------------------------------------------------------

def fig_retention_vs_paths(data: dict) -> None:
    fig, ax = plt.subplots(figsize=(COLUMN_IN, 2.55), constrained_layout=True)

    ideal_x = np.geomspace(1, 32, 128)
    ax.plot(ideal_x, 1 - 1 / ideal_x, color=INK, linestyle=(0, (2, 2)),
            linewidth=0.9, zorder=1)
    ax.annotate(r"$1-1/N$", xy=(11, 1 - 1 / 11), xytext=(9, 0.72),
                fontsize=7, color=INK_2)

    rng = np.random.default_rng(7)
    seen: list[str] = []
    for graph_id, oracle in data["oracle"].items():
        if oracle["retention"] is None:
            continue
        case = data["graphs"][graph_id]
        fam = case["family"]
        n = case["features"]["node_disjoint_paths"]
        jitter = np.exp(rng.uniform(-0.06, 0.06))  # multiplicative on log2 x
        ax.scatter(n * jitter, oracle["retention"], s=16,
                   marker=FAMILY_MARKER[fam],
                   facecolor=FAMILY_COLOR[fam], edgecolor="white",
                   linewidth=0.4, alpha=0.9, zorder=3,
                   label=fam.replace("_", " ") if fam not in seen else None)
        if fam not in seen:
            seen.append(fam)

    ax.annotate("bottleneck families:\nretention $\\approx 0$",
                xy=(1.05, 0.02), xytext=(1.15, 0.24), fontsize=6.5,
                color=INK_2,
                arrowprops=dict(arrowstyle="-", color=MUTED, linewidth=0.6))

    ax.set_xscale("log", base=2)
    ax.set_xticks([1, 2, 4, 8, 16, 32])
    ax.set_xticklabels(["1", "2", "4", "8", "16", "32"])
    ax.set_xlim(0.8, 40)
    ax.set_ylim(-0.05, 1.05)
    ax.set_xlabel("node-disjoint paths $N$")
    ax.set_ylabel("oracle retention")
    handles, labels = ax.get_legend_handles_labels()
    order = sorted(range(len(labels)), key=lambda i: labels[i])
    ax.legend([handles[i] for i in order], [labels[i] for i in order],
              loc="lower right", ncol=2, handletextpad=0.1,
              columnspacing=0.6, labelspacing=0.25, borderaxespad=0.2)
    _tidy(ax)
    fig.savefig(OUT / "fig_retention_vs_paths.pdf")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Fig: exploitability decay across the corpus
# ---------------------------------------------------------------------------

def fig_exploitability(data: dict) -> None:
    fig, ax_c = plt.subplots(figsize=(COLUMN_IN, 2.1),
                             constrained_layout=True)

    stride = 20
    curves = []
    for run in data["online"].values():
        curve = run["learning_curve"][::stride]
        turns = np.array([row["turn"] for row in curve]) / 1e3
        gap = np.array([max(row["exploitability"], 1e-6) for row in curve])
        curves.append(gap)
        ax_c.plot(turns, gap, color=AXIS, linewidth=0.5, alpha=0.45,
                  zorder=1)
    matrix = np.vstack(curves)
    ax_c.plot(turns, np.median(matrix, axis=0), color="#2a78d6",
              linewidth=1.6, zorder=3, label="median (50 graphs)")
    ax_c.fill_between(turns, np.percentile(matrix, 10, axis=0),
                      np.percentile(matrix, 90, axis=0), color="#2a78d6",
                      alpha=0.14, linewidth=0, zorder=2,
                      label="10–90%")
    ax_c.set_yscale("log")
    ax_c.set_xlabel(r"turn ($\times 10^3$)")
    ax_c.set_ylabel("Nash gap (averaged strategies)")
    ax_c.legend(loc="upper right", handlelength=1.4, borderaxespad=0.2)
    _tidy(ax_c)
    fig.savefig(OUT / "fig_exploitability.pdf")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Fig: exemplar topologies (bottleneck vs. many-route)
# ---------------------------------------------------------------------------

def _graph_layout(case: dict) -> dict[str, tuple[float, float]]:
    """Left-to-right layered layout by BFS depth from Alice."""
    edges = [(e["u"], e["v"]) for e in case["topology"]["edges"]]
    adjacency: dict[str, set[str]] = {}
    for u, v in edges:
        adjacency.setdefault(u, set()).add(v)
        adjacency.setdefault(v, set()).add(u)
    depth = {case["alice"]: 0}
    frontier = [case["alice"]]
    while frontier:
        nxt = []
        for node in frontier:
            for other in sorted(adjacency[node]):
                if other not in depth:
                    depth[other] = depth[node] + 1
                    nxt.append(other)
        frontier = nxt
    depth[case["bob"]] = max(depth.values())  # pin Bob to the right edge
    by_depth: dict[int, list[str]] = {}
    for node, d in depth.items():
        by_depth.setdefault(d, []).append(node)
    pos = {}
    for d, nodes in by_depth.items():
        for idx, node in enumerate(sorted(nodes)):
            pos[node] = (float(d), idx - (len(nodes) - 1) / 2.0)
    return pos


def _draw_exemplar(ax, case: dict) -> None:
    pos = _graph_layout(case)
    # Bottleneck internal nodes: shared by every candidate route.
    common = None
    for route in case["routes"]:
        internal = set(route["internal_nodes"])
        common = internal if common is None else common & internal
    common = common or set()
    for e in case["topology"]["edges"]:
        (x0, y0), (x1, y1) = pos[e["u"]], pos[e["v"]]
        ax.plot([x0, x1], [y0, y1], color=AXIS, linewidth=1.0, zorder=1)
    for node, (x, y) in pos.items():
        if node in (case["alice"], case["bob"]):
            face, edge, size = INK, INK, 130
        elif node in common:
            face, edge, size = BOTTLENECK_RED, BOTTLENECK_RED, 110
        else:
            face, edge, size = "#9ec5f4", "#2a78d6", 80
        ax.scatter(x, y, s=size, facecolor=face, edgecolor=edge,
                   linewidth=0.8, zorder=3)
        if node == case["alice"]:
            ax.annotate("A", pos[node], color="white", ha="center",
                        va="center", fontsize=7, fontweight="bold", zorder=4)
        elif node == case["bob"]:
            ax.annotate("B", pos[node], color="white", ha="center",
                        va="center", fontsize=7, fontweight="bold", zorder=4)
    ys = [y for _, y in pos.values()]
    xs = [x for x, _ in pos.values()]
    ax.set_xlim(min(xs) - 0.45, max(xs) + 0.45)
    ax.set_ylim(min(ys) - 0.7, max(ys) + 0.7)
    ax.set_axis_off()


def fig_exemplar_graphs(data: dict) -> None:
    fig, (ax_b, ax_p) = plt.subplots(
        1, 2, figsize=(COLUMN_IN, 1.75), constrained_layout=True,
        width_ratios=[1.15, 1.0])
    _draw_exemplar(ax_b, data["graphs"]["single_bottleneck_2_v0"])
    ax_b.set_title("(a) single bottleneck", fontsize=7.5, color=INK_2)
    _draw_exemplar(ax_p, data["graphs"]["disjoint_parallel_8_v0"])
    ax_p.set_title("(b) disjoint parallel ($N=8$)", fontsize=7.5,
                   color=INK_2)
    fig.savefig(OUT / "fig_exemplar_graphs.pdf")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Fig: learned-strategy heatmaps aggregated by family (turbo colormap)
# ---------------------------------------------------------------------------

def fig_strategy_heatmaps() -> None:
    action_rows = json.loads(
        (RUN / "dt" / "action_strategy_dt.json").read_text())["rows"]
    route_rows = json.loads(
        (RUN / "dt" / "route_strategy_dt.json").read_text())["rows"]

    kinds = ["no_attack", "edge_intercept_resend", "memory_degradation"]
    kind_labels = ["none", "edge IR", "memory"]
    eve_by_graph: dict[str, dict[str, float]] = {}
    fam_of: dict[str, str] = {}
    for row in action_rows:
        gid = row["graph_id"]
        fam_of[gid] = row["family"]
        kind = str(row["action_id"]).split(":", 1)[0]
        cell = eve_by_graph.setdefault(gid, dict.fromkeys(kinds, 0.0))
        cell[kind] += float(row["exp3_eve_empirical_prob"])
    eve = np.zeros((len(FAMILIES), len(kinds)))
    for i, fam in enumerate(FAMILIES):
        graphs = [g for g, f in fam_of.items() if f == fam]
        for j, kind in enumerate(kinds):
            eve[i, j] = float(np.mean([eve_by_graph[g][kind]
                                       for g in graphs]))

    max_rank = 8
    alice_by_graph: dict[str, list[float]] = {}
    for row in route_rows:
        alice_by_graph.setdefault(row["graph_id"], []).append(
            float(row["exp3_alice_empirical_prob"]))
    alice = np.zeros((len(FAMILIES), max_rank + 1))
    for i, fam in enumerate(FAMILIES):
        graphs = [g for g, f in fam_of.items() if f == fam]
        profiles = []
        for g in graphs:
            probs = sorted(alice_by_graph.get(g, []), reverse=True)
            prof = [probs[k] if k < len(probs) else 0.0
                    for k in range(max_rank)]
            prof.append(sum(probs[max_rank:]))
            profiles.append(prof)
        alice[i] = np.mean(np.asarray(profiles), axis=0)

    fig, (ax_e, ax_a) = plt.subplots(
        1, 2, figsize=(COLUMN_IN, 2.0), constrained_layout=True,
        width_ratios=[3, 9])
    cmap = plt.get_cmap("turbo")

    def draw(ax, data_matrix, col_labels):
        image = ax.imshow(data_matrix, cmap=cmap, vmin=0.0, vmax=1.0,
                          aspect="auto")
        ax.set_xticks(range(len(col_labels)))
        ax.set_xticklabels(col_labels, fontsize=6)
        ax.set_yticks(range(len(FAMILIES)))
        for i in range(data_matrix.shape[0]):
            for j in range(data_matrix.shape[1]):
                value = data_matrix[i, j]
                rgb = cmap(value)[:3]
                lum = 0.299 * rgb[0] + 0.587 * rgb[1] + 0.114 * rgb[2]
                ax.text(j, i, f"{value:.2f}".lstrip("0") or "0",
                        ha="center", va="center", fontsize=5,
                        color="black" if lum > 0.5 else "white")
        ax.tick_params(length=0)
        return image

    draw(ax_e, eve, kind_labels)
    ax_e.set_yticklabels([f.replace("_", " ") for f in FAMILIES],
                         fontsize=6.5)
    ax_e.set_title("(a) Eve: action type", fontsize=7, color=INK_2)
    ax_e.tick_params(axis="x", labelrotation=40)

    image = draw(ax_a, alice, [str(k) for k in range(1, max_rank + 1)]
                 + ["9+"])
    ax_a.set_yticklabels([])
    ax_a.set_title("(b) Alice: route rank", fontsize=7, color=INK_2)
    ax_a.set_xlabel("route rank (by learned probability)", fontsize=6.5)

    colorbar = fig.colorbar(image, ax=(ax_e, ax_a), fraction=0.035,
                            pad=0.015)
    colorbar.ax.tick_params(labelsize=6)
    colorbar.set_label("mean learned probability mass", fontsize=6.5)
    fig.savefig(OUT / "fig_strategy_heatmaps.pdf")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Fig: placeholder for the LLM interpretation-rubric evaluation
# ---------------------------------------------------------------------------

def fig_llm_rubric_placeholder() -> None:
    rubric = ["target awareness", "path faithfulness",
              "feature interpretation", "no hallucinated science"]
    models = ["local model A", "local model B", "local model C"]

    fig, ax = plt.subplots(figsize=(COLUMN_IN, 1.6), constrained_layout=True)
    for i in range(len(rubric)):
        for j in range(len(models)):
            ax.add_patch(plt.Rectangle(
                (j, i), 1, 1, facecolor="#f0efec", edgecolor="white",
                linewidth=1.5, hatch="///"))
            ax.text(j + 0.5, i + 0.5, "--", ha="center", va="center",
                    fontsize=8, color=MUTED)
    ax.set_xlim(0, len(models))
    ax.set_ylim(0, len(rubric))
    ax.invert_yaxis()
    ax.set_xticks(np.arange(len(models)) + 0.5)
    ax.set_xticklabels(models, fontsize=7)
    ax.set_yticks(np.arange(len(rubric)) + 0.5)
    ax.set_yticklabels(rubric, fontsize=7)
    ax.tick_params(length=0)
    for spine in ax.spines.values():
        spine.set_visible(False)
    ax.text(len(models) / 2, len(rubric) / 2, "PLACEHOLDER\nevaluation pending",
            ha="center", va="center", fontsize=9, color=INK_2,
            fontweight="bold", rotation=8,
            bbox=dict(boxstyle="round,pad=0.4", facecolor="white",
                      edgecolor=MUTED, alpha=0.9))
    fig.savefig(OUT / "fig_llm_rubric_placeholder.pdf")
    plt.close(fig)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    data = load_run()
    fig_attack_depth()  # not in the 4-page paper; kept for talks/appendix
    fig_convergence(data)
    fig_retention_vs_paths(data)
    fig_exploitability(data)
    fig_exemplar_graphs(data)
    fig_strategy_heatmaps()
    fig_llm_rubric_placeholder()
    for path in sorted(OUT.glob("*.pdf")):
        print(path.relative_to(REPO))


if __name__ == "__main__":
    main()
